name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    permissions:
      contents: write
      pull-requests: write
      checks: read

    steps:
      - name: Check if auto-merge label exists
        id: check-label
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const hasAutoMergeLabel = pr.labels.some(label => label.name === 'auto-merge');
            console.log(`Auto-merge label present: ${hasAutoMergeLabel}`);
            return hasAutoMergeLabel;

      - name: Wait for CI checks to complete
        if: steps.check-label.outputs.result == 'true'
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "Run Tests"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

      - name: Auto-approve PR
        if: steps.check-label.outputs.result == 'true'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}

      - name: Enable auto-merge
        if: steps.check-label.outputs.result == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.number }}
          merge-method: squash
