name: Security Audit

on:
  schedule:
    - cron: "0 2 * * 1"
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Run npm audit fix
        run: npm audit fix --dry-run

      - name: Check for vulnerabilities
        run: |
          if npm audit --audit-level=high --json | jq '.vulnerabilities | keys | length' | grep -v '^0$'; then
            echo "High severity vulnerabilities found!"
            exit 1
          fi
